### ISSUE TITLE
Use of buffers in WSASend is incorrect.

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#129]
Per the `WSASend` docs (https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsasend):

> For a Winsock application, once the WSASend function is called, the system owns these buffers and the application may not access them.

But we use `&[IoSlice<'_>]`, meaning that we don't own the buffers or even have unique access to them. We need to use `&mut [IoSlice<'_>]`, but this conflicts with the `io::Write::write_vectored` function signature.

Relevant code: https://github.com/rust-lang/socket2-rs/blob/dc82e662cda027f69abb75917777943fbffb8463/src/sys/windows.rs#L499-L516

**Comment by de-vri-es** [comment]
Hmm, I suspect this is a case of poor wording in the docs. I think it's overly protective. The only way reading these buffer objects from a different thread could be UB is if the OS is writing to them. However, if it did that I'd expect them to say that.

The wording is unfortunate, but I doubt this is really UB. It would be nice if someone with insider knowledge could confirm that though.

Note that the standard library does this the same way:
https://github.com/rust-lang/rust/blob/d4ea0b3e46a0303d5802b632e88ba1ba84d9d16f/library/std/src/sys/windows/net.rs#L315-L330

**Comment by Thomasdezeeuw** [comment]
Hasn't broken so far...
