### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#168]
It think the crate is nearly ready for a v0.4.0 release, the following is left to do.

* [x] Contributing guide. The crate has a somewhat unusual structure and this should be documented properly. Pr: #175.
* [x] Changelog. Currently the crate doesn't have one, but we've got to start one. Pr:  #177.

Moving the following to a future release:

* [ ] #166.
* [ ] #167.

**Comment by Thomasdezeeuw** [comment]
v0.4.0-alpha.1 has been released.

**Comment by tamird** [comment]
@Thomasdezeeuw would you mind releasing v0.4.0-alpha.2 to pick up the recent Fuchsia fixes?

**Comment by Thomasdezeeuw** [comment]
@tamird done.
