### ISSUE TITLE
CI check of Redox and Fuschia is broken

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#169]
See https://github.com/rust-lang/socket2/runs/1608768010. It has errors, but still gives an OK result.

**Comment by tamird** [comment]
Probably should keep this issue open until the CI is passing, yeah? For Fuchsia, that requires https://github.com/rust-lang/libc/pull/2010 and https://github.com/rust-lang/libc/pull/2011.

**Comment by Thomasdezeeuw** [comment]
@tamird I'm tracking it in https://github.com/rust-lang/socket2/issues/78.

**Comment by Thomasdezeeuw** [comment]
This is issue was just that even if the check failed the CI would report an OK status, #78 is tracking CI support for various targets.
