### ISSUE TITLE
Support for connect_timeout in 0.4

### ISSUE THREAD

**Issue by oblique** [rust-lang/socket2#190]
As I saw in 0.4 changelogs `Socket::connect_timeout` was removed because it was not a low-level function but a combination of system calls. This is true, however a lot of people may need this functionality.

For someone to implement this and make it cross-platform, it will be troublesome. So can we have it back? Maybe we can have it in a new crate? For example in `socket2-util` crate and in `SocketExt` trait.

**Comment by Thomasdezeeuw** [comment]
Ok, `Socket::connect_timeout` can come back. @oblique do you want to create a pr for it? The code was removed in commit 57d29ea60c86a565e6eda4abc48c0e6698bdbea2, but it can do with a bit of an update.

**Comment by oblique** [comment]
Yes sure. Should I put it in `Socket` struct?

**Comment by Thomasdezeeuw** [comment]
You can put on the `Socket` struct.
