### ISSUE TITLE
Add Support for ICMPv6 filters on raw sockets

### ISSUE THREAD

**Issue by zaphar** [rust-lang/socket2#199]
Since ICMPv6 has man more message types than ICMPv4 a raw ICMPv6 socket will by default receive all the ICMPv6 messages. While it's possible to filter them all yourself it seems like it might be better to add support for the ICMPv6 filters as referenced here: https://tools.ietf.org/html/rfc2292#section-3.2 I believe windows has a similar facility as well.

**Comment by Thomasdezeeuw** [comment]
Socket2 doesn't implement the RFC itself, it's a wrapper around system calls. So if the OSs provide a way to filter ICMP packets feel free to open a pr to add this.

**Comment by Thomasdezeeuw** [comment]
Due to the lack of progress I'm going to close it. Any more discussion or contributions are of course always welcome.
