### ISSUE TITLE
Support basic SCTP over plain/legacy sockets

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/socket2#202]
Using just the basic socket APIs like connect/bind/send/etc it is possible to interact with SCTP sockets. While you don't get the full SCTP feature-set when using them, nevertheless they do work, so... thoughts?

**Comment by Thomasdezeeuw** [comment]
Prs would be accepted.

**Comment by Thomasdezeeuw** [comment]
Due to the lack of progress I'm going to close it. Any more discussion or contributions are of course always welcome.
