### ISSUE TITLE
Make clear that Unix Sockets are not supported.

### ISSUE THREAD

**Issue by cheako** [rust-lang/socket2#209]
I had to poke around a bit in the API documentation to reach the conclusion that Sockets2 wasn't what I wanted.

I'm looking for a crate that combines Inet and Unix sockets into a single abstraction, pivoting on a feature.

**Comment by Thomasdezeeuw** [comment]
But Unix sockets are supported, via `Socket::unix` or `Socket::pair`. What functionality are you missing?

**Comment by Thomasdezeeuw** [comment]
@cheako I don't what I can do for this issue, Unix sockets are very much supported.
