### ISSUE TITLE
Looking for additional maintainers

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#211]
Currently I'm the only person that maintain this crate. Since the number of issues/prs is low this isn't a problem from a work-load perspective, but code I write often doesn't get a proper review as there is no-one to do so (beside myself).

If you're willing to help in reviewing please leave a comment.

If you have knowledge about a specific OS, especially a lesser used one, and you're willing to spend some time reviewing prs involving the OS please leave a comment.

**Comment by YorickPeterse** [comment]
I use socket2 for https://inko-lang.org/ / https://gitlab.com/inko-lang/inko. I also have quite a bit of experience with the POSIX socket API (a few years back I re-implemented the Ruby socket API in Ruby itself for [Rubinius](https://github.com/rubinius/rubinius)). I'm happy to help out where possible :smiley:

**Comment by Thomasdezeeuw** [comment]
@YorickPeterse good to hear. Socket2 isn't a lot of work to maintain, it's mainly for the case when I'm not available. Feel free to comment/review issues and prs when you have some time.

**Comment by chansuke** [comment]
I'd be happy to help out too 🥰
