### ISSUE TITLE
How should I create a PF_NETLINK socket by socket2?

### ISSUE THREAD

**Issue by ChenhuiZhang** [rust-lang/socket2#219]
The Domain seems only support IPv4 and IPv6, could I change the value to NETLINK? Thanks.

**Comment by Thomasdezeeuw** [comment]
You can use `let domain: Domain = libc::AF_NETLINK.into()` to create a `Domain` from an arbitrary `i32` as `Domain` implements `From<i32>`.

Also an addition of a `NETLINK` constant would be welcome.

**Comment by ChenhuiZhang** [comment]
Thanks for the info. Now it works.
