### ISSUE TITLE
error[E0658]: `match` is not allowed in a `const fn`

### ISSUE THREAD

**Issue by shangsony** [rust-lang/socket2#220]
error[E0658]: `match` is not allowed in a `const fn`
   -->/socket2-0.4.0/src/lib.rs:156:9
    |
156 | /         match address {
157 | |             SocketAddr::V4(_) => Domain::IPV4,
158 | |             SocketAddr::V6(_) => Domain::IPV6,
159 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

   Compiling time v0.1.43
error: aborting due to previous error

**Comment by Thomasdezeeuw** [comment]
Socket2 v0.4 requires rustc v1.46.

**Comment by tychota** [comment]
Note: the readme speak about **minimum** supported version of rust.

![image](https://user-images.githubusercontent.com/13785185/119246405-a34f7180-bb81-11eb-9bf8-a6eda42618d3.png)

For me that means that new version should works.

Except they doesn't:

![image](https://user-images.githubusercontent.com/13785185/119246378-5cfa1280-bb81-11eb-8173-5ce29f8b6a71.png)
![image](https://user-images.githubusercontent.com/13785185/119246383-6a170180-bb81-11eb-8b40-aa5eac7b9bbd.png)

can you consider making compatibility to new rust version a goal to v0.5 ?

**Comment by tychota** [comment]
@Thomasdezeeuw can you reopen ?

**Comment by Thomasdezeeuw** [comment]
@tychota I think you're doing something wrong. socket2 rust on rustc 1.46 stable. Are you sure you're calling the same rustc?

P.S. could you also not use images of texts, it's very annoying to read.

**Comment by tychota** [comment]
@Thomasdezeeuw i will try to make a minimal example that reproduce and then report here.

My bad for the image, i will paste texte next time.

**Comment by Thomasdezeeuw** [comment]
@tychota you're really running a different/incorrect rustc binary. Per the 1.46 blogpost: https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html#const-fn-improvements, `match` statements are `const`, which the error is about.

**Comment by tychota** [comment]
All clear. I indeed has an old rust binary somewhere.

Sorry for the noise.
