### ISSUE TITLE
Rename Domain to Family

### ISSUE THREAD

**Issue by KaiJewson** [rust-lang/socket2#225]
The word "domain" is less common than "family" when talking about this option: in `AF_*`, `sa_family_t`, [Winsock2's `socket` docs](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket) and [socket(7)](https://man7.org/linux/man-pages/man7/socket.7.html). As far as I can tell the only time `domain` is actually used is in the parameter listed on `socket(2)`, but it still refers to the parameter as a family in its description. The `AF_*` constants in libc are currently not `sa_family_t`s but it seems [that was a mistake](https://github.com/rust-lang/libc/issues/468).

Additionally `SockAddr::family` should be made to return a `Family`, which would be more convenient, and the `From<c_int> for Domain` impl should be replaced with `From<sa_family_t> for Family`.

**Comment by Thomasdezeeuw** [comment]
I don't really have a strong preference here. But the domain terminology is used in `SO_DOMAIN`, which is the name of the socket option to retrieve the domain (e.g. `AF_INET6`).

The `socket(7)` manual uses the both, e.g. section Socket address structures (emphasis mine):
> Each socket **domain** has its own format for socket addresses, with
> a **domain**-specific address structure.  Each of these structures
> begins with an integer **"family"** field (typed as sa_family_t) [...]

So I think you're both used.

As for the switch to `sa_family_ts`: `socket(2)` accepts an `int`, which is the main use of `Domain` so I think it's best to keep that as is.

**Comment by KaiJewson** [comment]
Ah, if you want to keep `Socket::new`'s first parameter as an `int` it's probably best to keep it the way it is then.
