### ISSUE TITLE
Unsoundness in `<SockRef as From<&AsRawFd>>::from`

### ISSUE THREAD

**Issue by coolreader18** [rust-lang/socket2#229]
You can do something like:
```rust
let sock = socket2::SockRef::from(&-1);
assert!(Some(sock).is_none());
```
With the changes in #222

**Comment by Thomasdezeeuw** [comment]
This is the same problem as being discussed in #229, `SockRef::from` needs to ensure the `RawFd` is valid, but currently doesn't.

**Comment by Thomasdezeeuw** [comment]
Whoops I meant #218.

**Comment by coolreader18** [comment]
Ah, sorry about that.

**Comment by coolreader18** [comment]
Oh, wait, I'll add this to that discussion, but this is actually *unsound*, not just questionably unsafe - because of the niche optimization from #222, you can create an invalid value in safe code.

**Comment by Thomasdezeeuw** [comment]
> Oh, wait, I'll add this to that discussion, but this is actually _unsound_ language-wise, not just questionably unsafe/non-private - because of the niche optimization from #222, you can create an invalid value in safe code.

You're right using `-1` is even worse, but as #222 is talking about a redesign I though it best to not have two concurrent threads talking about the same thing. But this is definitely blocking a v0.4.1 release (which would include #222).
