### ISSUE TITLE
why  sockaddr.as_socket_ipv4()   output None  in  the following code ?

### ISSUE THREAD

**Issue by zrz4066** [rust-lang/socket2#239]
why  sockaddr.as_socket_ipv4()   output None  in  the following code ?  it should  return remote IP address.

let (size, sockaddr) = socket.recv_from(x.as_mut()).expect("cannot recv");
        let now = chrono::Local::now();
        let resp:String=unsafe {
            let mut ss=Vec::<char>::new();
            for i in 0..size{
                let x2 =  x[i].assume_init() as char;
                //println!("{:?}",x2);
                ss.push(x2);
            }
            ss[0..ss.len()].iter().collect()
        };
        
        println!("{:?}, {:?} bytes from {:#?}, {:?}", now, size, sockaddr.as_socket_ipv4(),resp);

result:
      2021-05-31T09:54:34.687982100+08:00, 37 bytes from None, "OK+GPS,9,0.0,0,0.0,0,0-0-0 0:0:0,5e\r\n"

**Comment by Thomasdezeeuw** [comment]
Is `socket` a UDP socket? Could you show the creation of the socket?

**Comment by zrz4066** [comment]
socket is TCP socket. Here is the test code

fn main() //-> std::io::Result<()> 
{
// This IP is unroutable, so connections should always time out.
    let addr = "192.168.3.202:8888".parse::<SocketAddr>().unwrap().into();

    let socket = Socket::new(Domain::IPV4, Type::STREAM, None).unwrap();
    socket.reuse_address();
    match socket.connect_timeout(&addr, Duration::from_millis(250)) {
        Ok(o) => {println!("o:{:?}",o);},
        Err(ref e) if e.kind() == io::ErrorKind::TimedOut => {}
        Err(e) => panic!("unexpected error {}", e),
    }
    let mut buffer = [0u8; 1600];
    loop {
        let mut cmd="at+hb".as_bytes();
        let result=socket.send(cmd);

        if let Ok(ss)=result{
            println!("cmd:{}", ss);
        }

        let mut x:[MaybeUninit<u8>;300] = unsafe {
            MaybeUninit::uninit().assume_init()
        };

        let (size, sockaddr) = socket.recv_from(x.as_mut()).expect("cannot recv");
        let now = chrono::Local::now();
        let resp:String=unsafe {
            let mut ss=Vec::<char>::new();
            for i in 0..size{
                let x2 =  x[i].assume_init() as char;
                //println!("{:?}",x2);
                ss.push(x2);
            }
            ss[0..ss.len()].iter().collect()
        };
        
        println!("{:?}, {:?} bytes from {:#?}, {:?}", now, size, sockaddr.as_socket_ipv4(),resp);
    }

}

**Comment by zrz4066** [comment]
socket is TCP socket. Here is the test code

fn main() //-> std::io::Result<()> 
{
// This IP is unroutable, so connections should always time out.
    let addr = "192.168.3.202:8888".parse::<SocketAddr>().unwrap().into();

    let socket = Socket::new(Domain::IPV4, Type::STREAM, None).unwrap();
    socket.reuse_address();
    match socket.connect_timeout(&addr, Duration::from_millis(250)) {
        Ok(o) => {println!("o:{:?}",o);},
        Err(ref e) if e.kind() == io::ErrorKind::TimedOut => {}
        Err(e) => panic!("unexpected error {}", e),
    }
    let mut buffer = [0u8; 1600];
    loop {
        let mut cmd="at+hb".as_bytes();
        let result=socket.send(cmd);

        if let Ok(ss)=result{
            println!("cmd:{}", ss);
        }

        let mut x:[MaybeUninit<u8>;300] = unsafe {
            MaybeUninit::uninit().assume_init()
        };

        let (size, sockaddr) = socket.recv_from(x.as_mut()).expect("cannot recv");
        let now = chrono::Local::now();
        let resp:String=unsafe {
            let mut ss=Vec::<char>::new();
            for i in 0..size{
                let x2 =  x[i].assume_init() as char;
                //println!("{:?}",x2);
                ss.push(x2);
            }
            ss[0..ss.len()].iter().collect()
        };
        
        println!("{:?}, {:?} bytes from {:#?}, {:?}", now, size, sockaddr.as_socket_ipv4(),resp);
    }

}

**Comment by zrz4066** [comment]
My Os is 64-bit Win10

**Comment by Thomasdezeeuw** [comment]
@zrz4066 TCP is a stream based socket which means it only sends and receives packets from a single peer. Because it can only send to or receive from a single peer the address never changes, so `recv_from` doesn't return the address each time. For TCP socket you should use [`Socket::recv`](https://docs.rs/socket2/0.4.0/socket2/struct.Socket.html#method.recv) which only returns the number of bytes received.

If you need the address you'll need to keep track of that when connection or accepting the connection.
