### ISSUE TITLE
```SockAddr::unix()```  not found  on linux

### ISSUE THREAD

**Issue by NeilBotelho** [rust-lang/socket2#247]
When trying to use the  [unix()](https://docs.rs/socket2/0.4.0/socket2/struct.SockAddr.html#method.unix)  constructor for SockAddr, I get the error:
```
error[E0599]: no function or associated item named `unix` found for struct `SockAddr` in the current scope
  --> src/main.rs:20:30
   |
20 |     let addr_srv = SockAddr::unix(ADDR).unwrap();
   |                              ^^^^ function or associated item not found in `SockAddr`
```
where ```ADDR``` is of type ```std::path::Path```

Additionally after running cargo doc, ```SockAddr::unix()``` is not in the documentation even though it is in the online documentation.

### System:
- cargo 1.52.0
- rustc 1.52.1 
- socket2  0.4.0
- Linux arch 5.10.47-1-lts

I have also confirmed that the target-family flag is set to unix in cargo.

**Comment by Thomasdezeeuw** [comment]
You'll need to enable the `all` feature to opt in API which isn't available on all OSs, such as this Unix only API.
