### ISSUE TITLE
Socket2-0.4.0 throwing error with "error[E0432]: unresolved import `crate::sys`"

### ISSUE THREAD

**Issue by chowdhury-bc** [rust-lang/socket2#250]
|
5 | use crate::sys::{
  |            ^^^
  |            |
  |            unresolved import
  |            help: a similar path exists: `crate::socket::io::sys`

I have latest version rustc(1.53) and cargo(1.53) I am running it on macOS.

thank you for your help

**Comment by Thomasdezeeuw** [comment]
Can you provide some more context? I can't really see the source of the error.

**Comment by chowdhury-bc** [comment]
Hi thanks for the response,
i am trying to build-bpf from this source, 
https://github.com/solana-labs/example-helloworld/tree/master/src/program-rust

so if i run cargo build-bpf i get the above error. I have tried with both version of socket2 but same error.

**Comment by Thomasdezeeuw** [comment]
Are you building for a target that is unsupported? You said your running on macOS, but if you building with a different target it might not be supported.

**Comment by ArnaudAmun** [comment]
Hi, I have the same issue.
Adding Solana-Cli to cargo.toml in an empty project and it failed to compile socket2 with the same error: `use of an undeclared crate or module sys`.
Using cargo build-bpf on a Linux machine

**Comment by ArnaudAmun** [comment]
It also complains about the l.1648-1653: `expected struct Socket, found ()` and same for the other types.

**Comment by Thomasdezeeuw** [comment]
Are you targeting an unsupported OS or special environment? I need more information, preferably an environment that can reproduce the error. I'm not going to debug another project with thousands of lines.

**Comment by Thomasdezeeuw** [comment]
Since there seems no more response I'm going to close this. It seems that your using a target that is neither Unix or Windows, which at the moment isn't supported.
