### ISSUE TITLE
Use of set_only_v6() in example code

### ISSUE THREAD

**Issue by cmcqueen** [rust-lang/socket2#259]
In the [example](https://docs.rs/socket2/0.4.1/socket2/#examples) code in `lib.rs`, it has these lines:

    socket.bind(&address.into())?;
    socket.set_only_v6(false)?;

Isn't it necessary for the call to `set_only_v6()` to be *before* the `bind()`?

**Comment by Thomasdezeeuw** [comment]
Yes. Want to send a pr?
