### ISSUE TITLE
Consider moving to Tokio organisation

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#269]
The Tokio organisation has offered to support the socket2 library. I'm creating this issue to have an open discussion about it.

In the past their was were some opinions against doing this, I want to know if these are still present.

/cc @Darksonn

**Comment by Thomasdezeeuw** [comment]
It's been a month, little to no comments. Not sure how to interpret that.

@rust-lang/libs team how do you feel?

**Comment by robjtede** [comment]
I think that the rust community would, buy-and-large, trust the project that the rust compiler itself sits in (ie. rust-lang). Socket2 _feels_ like a project that has a wider scope than Tokio since it is more general in purpose. I would be surprised, even, to discover that such a project resides in Tokio's scope.

**Comment by taiki-e** [comment]
I believe that what is proposed in [RFC3119 "Rust crate ownership policy"](https://rust-lang.github.io/rfcs/3119-rust-crate-ownership.html) (merged a few months ago) is enough to address [the original concerns from the tokio team](https://github.com/tokio-rs/mio/pull/1431#issuecomment-763861677), but it is not clear how long it will take to do.

**Comment by Thomasdezeeuw** [comment]
> I believe that what is proposed in [RFC3119 "Rust crate ownership policy"](https://rust-lang.github.io/rfcs/3119-rust-crate-ownership.html) (merged a few months ago) is enough to address (most of?) [the original concerns from the tokio team](https://github.com/tokio-rs/mio/pull/1431#issuecomment-763861677), but it is not clear how long it will take to do.

The problem with RFC3119 is that I haven't seen a lot work being done in the area. I think generally people like the idea, but I'm not sure how time is spend actually implementing it all, as per the (lack of) comments on the tracking issue: https://github.com/rust-lang/rust/issues/88867.

For I think the plan is to not move socket2 and instead invite some maintainers from Tokio to this repo.

**Comment by Thomasdezeeuw** [comment]
Closing this as we're not moving the socket2 crate.
