### ISSUE TITLE
How to use MaybeUninit on the some functions

### ISSUE THREAD

**Issue by eddi0815** [rust-lang/socket2#270]
Hallo,

as the title says I don't know how to use MaybeUninit in an idiomatic way. It is the first time I need to use it because of some functions in socket2. After some reading I implemented the following code snippet:

```rust
fn receive(&self) -> Result<Vec<u8>> {
    let mut buffer: [u8; 4096] = [0; 4096];   
    
    let buffer = unsafe { &mut *(&mut buffer as *mut [u8; 4096] as *mut [MaybeUninit<u8>; 4096]) };

    let received = self.socket.recv( buffer)?;

    let buffer = unsafe { *(buffer as *mut [MaybeUninit<u8>; 4096] as *mut [u8; 4096]) };

    Ok(buffer[..received].to_vec())
}
```
Is this the way to use it? Is there an approach to convert from MaybeUninit and to it witthout this unsafe blocks and this ugly casting? 

Thanks

**Comment by Thomasdezeeuw** [comment]
Hi @eddi0815 working with uninitialised buffer is a bit of a pain on stable Rust at the moment, but improvements are coming. For example using the unstable [`Vec::spare_capacity_mut`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.spare_capacity_mut) function (but you could implement that yourself in a couple of lines).

```rust
// Required for https://doc.rust-lang.org/std/vec/struct.Vec.html#method.spare_capacity_mut.
#![feature(vec_spare_capacity)]

use std::io;

use socket2::Socket;

fn receive(socket: &Socket) -> io::Result<Vec<u8>> {
    let mut buffer = Vec::with_capacity(4096);
    let received = socket.recv(buffer.spare_capacity_mut())?;
    // SAFETY: just received into the `buffer`.
    unsafe {
        buffer.set_len(received);
    }
    Ok(buffer)
}
```

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cd9fa7367e8d5162eb43c1ab4b44f108.

**Comment by eddi0815** [comment]
Hi @Thomasdezeeuw ,

thanks for the hint. This looks much cleaner.
