### ISSUE TITLE
Cannot compile in Raspberry(arm64)

### ISSUE THREAD

**Issue by lams2135** [rust-lang/socket2#277]
Compiling socket2 v0.4.1
error: attributes are not yet allowed on `if` expressions
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.1/src/sys/unix.rs:878:5
    |
878 |     #[cfg(not(any(target_os = "haiku", target_os = "openbsd")))]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `socket2`.

**Comment by Thomasdezeeuw** [comment]
What rustc are you using? We require at least rustc 1.46.

**Comment by Thomasdezeeuw** [comment]
@lams2135 I think if you update your rustc version this should be resolved. I'm closing this for now, but if its still an issue please reopen it.

**Comment by lams2135** [comment]
thank you @Thomasdezeeuw , I updated rustc then resolve this issue.
