### ISSUE TITLE
Support TCP_CORK, TCP_THIN_LINEAR_TIMEOUTS and TCP_QUICKACK

### ISSUE THREAD

**Issue by eddi0815** [rust-lang/socket2#285]
Hallo,

for my project I need to use the socket options TCP_CORK, TCP_THIN_LINEAR_TIMEOUTS and TCP_QUICKACK and I'd like to implement them for socket2. As far as I know these options are Linux only.

Disclaimer: I am quite new to Rust and this is my first PR for a Rust project.

I am not sure where to implement this stuff in https://github.com/rust-lang/socket2/blob/master/src/sys/unix.rs and https://github.com/rust-lang/socket2/blob/master/src/socket.rs. I found a **unix only** section but I don't know if these options are available for other Unix-like systems as well. 

My first though is to put the option flags into https://github.com/rust-lang/socket2/blob/master/src/sys/unix.rs#L1004 and mark them with `#[cfg(target_os = "linux")]` and put the implementation into https://github.com/rust-lang/socket2/blob/master/src/socket.rs#L1445 and mark them also with the linux target.

The implementation itself would be more or less a copy/paste of nodelay/set_nodelay. 

What are your thoughts about it? 

Thanks

**Comment by Thomasdezeeuw** [comment]
> Hallo,
> 
> for my project I need to use the socket options TCP_CORK, TCP_THIN_LINEAR_TIMEOUTS and TCP_QUICKACK and I'd like to implement them for socket2. As far as I know these options are Linux only.
> 
> Disclaimer: I am quite new to Rust and this is my first PR for a Rust project.
> 
> I am not sure where to implement this stuff in https://github.com/rust-lang/socket2/blob/master/src/sys/unix.rs and https://github.com/rust-lang/socket2/blob/master/src/socket.rs. I found a **unix only** section but I don't know if these options are available for other Unix-like systems as well.

They should indeed for into the Unix only block here: https://github.com/rust-lang/socket2/blob/271fd2e878be19aab9bbd416ea18ed54ac31af61/src/sys/unix.rs#L1003-L1004 Please keep them in alphabetical order.

> My first though is to put the option flags into https://github.com/rust-lang/socket2/blob/master/src/sys/unix.rs#L1004 and mark them with `#[cfg(target_os = "linux")]` and put the implementation into https://github.com/rust-lang/socket2/blob/master/src/socket.rs#L1445 and mark them also with the linux target.

That the right approach, also see `set_mark`: https://github.com/rust-lang/socket2/blob/271fd2e878be19aab9bbd416ea18ed54ac31af61/src/sys/unix.rs#L1264-L1284 Both Android and Fuchsia are Linux based/Linux compatible so try adding should to the `target_os` as well. If they don't support them that no problem either. You can use `make check_all_targets` for this: https://github.com/rust-lang/socket2/blob/271fd2e878be19aab9bbd416ea18ed54ac31af61/Makefile#L14-L20

> The implementation itself would be more or less a copy/paste of nodelay/set_nodelay.
> 
> What are your thoughts about it?

Sounds good!

> Thanks
