### ISSUE TITLE
does socket2 support select?

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/socket2#296]
Is there any support of `select` (as in Unix) or something similar?

**Comment by Thomasdezeeuw** [comment]
Not in socket2, I would consider it out of scope for socket2. However if you're looking for something like `epoll`/`kqueue` you can consider [Mio](https://docs.rs/mio).

**Comment by keepsimple1** [comment]
socket2 already depends on `libc` and `winapi`, thus has the tools needed to support something like `select`.  In fact, the `poll_connect` function seems to do something similar, on [windows](https://github.com/rust-lang/socket2/blob/527292127f5a92db6bfdffbf1df9fd05c83935b1/src/sys/windows.rs#L263-L266) and on [Unix](https://github.com/rust-lang/socket2/blob/527292127f5a92db6bfdffbf1df9fd05c83935b1/src/sys/unix.rs#L610).

**Comment by Thomasdezeeuw** [comment]
> socket2 already depends on `libc` and `winapi`, thus has the tools needed to support something like `select`. In fact, the `poll_connect` function seems to do something similar, on [windows](https://github.com/rust-lang/socket2/blob/527292127f5a92db6bfdffbf1df9fd05c83935b1/src/sys/windows.rs#L263-L266) and on [Unix](https://github.com/rust-lang/socket2/blob/527292127f5a92db6bfdffbf1df9fd05c83935b1/src/sys/unix.rs#L610).

I know and I felt that was out of scope already, but the std lib's `TcpSocket`also had it, so we decided in the end to add it back again. But `select` is really out of scope for socket2.

**Comment by keepsimple1** [comment]
I understand that. On the other hand, it seems to me that Rust net/socket ecosystem fragmented too much. The `std::net` is missing lots of important features, while 3rd-party crates are overlapping each other and often times we have to pull in a new dependency to just call a single common function.

It's not `socket2`'s fault. But I am worried that the situation hurts the productivity of many Rust users.  The ideal case is that `std::net` can be fixed to cover all the bases, but I don't know if that will ever happen. Sorry for ranting.
