### ISSUE TITLE
send_to fails due to invalid SockAddr

### ISSUE THREAD

**Issue by Yneth** [rust-lang/socket2#300]
I am using `SocketAddrV4.into()` which is passed to `socket.send_to`.
And according to https://github.com/rust-lang/socket2/blob/master/src/sockaddr.rs#L238
`sin_len` is always 0 which causes 
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', src/main.rs:55:43
```

**Comment by Yneth** [comment]
is there any quick fix to this?

**Comment by Yneth** [comment]
I was wrong, it is not the root cause of error described earlier.

**Comment by Thomasdezeeuw** [comment]
Could you share some code and context (OS, etc.) because it's highly unlike the socket address conversion is at fault here.

**Comment by Yneth** [comment]
yeah, this error code refers to EINVAL (linux.man)[https://linux.die.net/man/3/sendto].
I am using `set_header_included` meaning that I am manually creating a tcp ip packet.

**Comment by Yneth** [comment]
solution to the problem is to use little endian for checksums and ip_len on macos
as per
* https://cseweb.ucsd.edu//~braghava/notes/freebsd-sockets.txt
* https://stackoverflow.com/a/7160206
* Steven's "Unix Network Programming" Volume I Chapter 25 "Raw socket" 2nd edition
