### ISSUE TITLE
Release v0.4.5 did a break change

### ISSUE THREAD

**Issue by bachue** [rust-lang/socket2#308]
The PR "Replace `winapi` dependency with `windows-sys`"  (https://github.com/rust-lang/socket2/pull/303) breaks public apis, cause [`dns-lookup`](https://github.com/keeperofdakeys/dns-lookup) are failed to compile on windows https://github.com/keeperofdakeys/dns-lookup/issues/22. `dns-lookup` calls `getnameinfo` from `winapi`, but now `socket2` exports `SockAddr` from `windows-sys`, which are incompatible with `SockAddr` from `winapi`.

**Comment by Thomasdezeeuw** [comment]
I've yanked v0.4.5 for now.

**Comment by bachue** [comment]
@Thomasdezeeuw  👍

**Comment by sn99** [comment]
@Thomasdezeeuw I am working on shifting `dns-lookup` from `winapi` to `window_sys`, I am using your master branch instead of crates.io and it seems to be working, I will make a pull in `dns-lookup` soon.

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw I am working on shifting `dns-lookup` from `winapi` to `window_sys`, I am using your master branch instead of crates.io and it seems to be working, I will make a pull in `dns-lookup` soon.

Sounds good, but unfortunately we still can't make a breaking change in a v0.4.x release, so the switch to window_sys will have to go into v0.5.

**Comment by sn99** [comment]
> > @Thomasdezeeuw I am working on shifting `dns-lookup` from `winapi` to `window_sys`, I am using your master branch instead of crates.io and it seems to be working, I will make a pull in `dns-lookup` soon.
> 
> Sounds good, but unfortunately we still can't make a breaking change in a v0.4.x release, so the switch to window_sys will have to go into v0.5.

Oh yeah, no problem, just wanted to inform you about the change in dns-lookup

**Comment by Thomasdezeeuw** [comment]
> For future reference, since socket2 is exposing the SOCKADDR type from the underlying windows_sys library via getaddrinfo/getnameinfo, any change to SOCKADDR in windows_sys will also change the SOCKADDR that socket2 uses. Apparently windows_sys has changed SOCKADDR [A](https://docs.rs/windows-sys/0.42.0/windows_sys/Win32/Networking/WinSock/struct.SOCKADDR.html) [Few](https://docs.rs/windows-sys/0.45.0/windows_sys/Win32/Networking/WinSock/struct.SOCKADDR.html) [Times](https://docs.rs/windows-sys/0.48.0/windows_sys/Win32/Networking/WinSock/struct.SOCKADDR.html) recently, which means the exact subversion of windows_sys needs to match in libraries using socket2.
> 
> Since both windows_sys and socket2 are version 0.X.Y, I'd suggest that anybody using these libraries hard code socket2 and windows_sys versions explicitly. We'll likely need to wait till both libraries are version 1.0 before we can get stable APIs.

Those changes are just aliases for the same underlying types. The actual layout of the struct is fixed as any changes to it would break ABI compatibility with Windows' system calls. So I don't think this is an issue.

Relying on 0.x libraries, especially exposing them in the public API as socket2 does, isn't great, but having to maintain these (public) types/type aliases ourselves wouldn't be an improvement either.
