### ISSUE TITLE
API to clone/copy a SockAddr?

### ISSUE THREAD

**Issue by nathaniel-bennett** [rust-lang/socket2#310]
Is there any way to create a new copy of a `SockAddr` from an existing one? I've searched through documentation pretty extensively, but there doesn't appear to be any API to do it as it stands.

It looks like `sockaddr_storage` and `socklen_t` have both `Copy` and `Clone` traits implemented for them, and in its current form `SockAddr` is composed of just those two values, so unless there's some compatibility reason for not adding them it seems like it would be pretty straightforward to add `Copy`/`Clone` traits to `SockAddr`. I would be happy to help out with implementing something like this if wanted :).

**Comment by Thomasdezeeuw** [comment]
A pr to add `Clone` would be accept. I'm sure about `Copy`, it's a little big I think.

**Comment by Thomasdezeeuw** [comment]
Fixed in #311.
