### ISSUE TITLE
recvmmsg, control messages, timestamps

### ISSUE THREAD

**Issue by pacak** [rust-lang/socket2#312]
I'm trying to implement something to support zero copy `recvmmsg` (and possibly `sendmmsg`) in *nix along with support for hardware/software timestamps. This will require adding support for control messages and some related things. I wonder how well it fits with this crate philosophy.

Timestamping and `recvmmsg` are independent changes.

Should I try add it to this crate or is it best to implement it separately?

**Comment by notgull** [comment]
This crate aims for bare minimums, I'd say to implement it in a separate crate. Alternatively you could use `AsRawFd` plus [`nix`](https://docs.rs/nix/latest/nix/) to do it safely.

**Comment by pacak** [comment]
I already added support for timestamping to nix and got it merged upstream, it's just nix already implements recvmmsg but it's very strange. Anyway, thanks for the reply I guess this ticket can be closed unless there's other opinions.

**Comment by Thomasdezeeuw** [comment]
We can add a wrapper around the system call, it's just a question of how much would this wrapper do, for example to achieve safety or cross platform support. We try to adhere by 1 function = 1 system call, but that's not always possible. @pacak if you have an idea/design on how socket2 would support the system calls I would be open to consider them.

**Comment by pacak** [comment]
I don't think it's as simple as that hence the ticket. Getting timestamps would require allocating message buffers, providing a way to get them back, etc. Plus it would be nice to let the user decide what headers to request/allocate.
