### ISSUE TITLE
Close socket on Drop?

### ISSUE THREAD

**Issue by aviramha** [rust-lang/socket2#330]
Right now there's no `Drop` implementation for `Socket`. I think it should have so it can close it when it's dropped.
Would you accept a PR adding this?

**Comment by Thomasdezeeuw** [comment]
We use a `TcpStream` to represent the `Socket`, so it handles closing the socket for us: https://github.com/rust-lang/socket2/blob/eaa6300e13d7ed421a3df2fe0149b7a54956b84c/src/socket.rs#L73-L77
