### ISSUE TITLE
Fix cfg target checks for TcpKeepalive

### ISSUE THREAD

**Issue by MortronMeymo** [rust-lang/socket2#337]
The cfg target checks for the TcpKeepalive feature are contradicting each other.

The `interval` member of the `TcpKeepalive` struct uses
```
#[cfg(not(any(target_os = "redox", target_os = "solaris")))]
```

The setter for the field (`with_interval`) uses
```  
#[cfg(all(
        feature = "all",
        any(
            target_os = "dragonfly",
            target_os = "freebsd",
            target_os = "fuchsia",
            target_os = "linux",
            target_os = "netbsd",
            target_vendor = "apple",
            windows,
        )
    ))]
```

And the code in sys::set_tcp_keepalive (unix.rs) uses:
```   
 #[cfg(any(
        target_os = "android",
        target_os = "dragonfly",
        target_os = "freebsd",
        target_os = "fuchsia",
        target_os = "illumos",
        target_os = "linux",
        target_os = "netbsd",
        target_vendor = "apple",
    ))]
```

So in all three places whether the `interval` is supported or not is determined differently.

The end result is if you pick for example `android` as your target, than the member is there, the setter is missing and the code to actually set the value is there, making this unusable on android despite being supported by android.

**Comment by MortronMeymo** [comment]
I'm not sure which of the different cfg checks is the best one....

**Comment by Thomasdezeeuw** [comment]
The public needs Android here (and just below it): https://github.com/rust-lang/socket2/blob/acde0dae0cc5979ce6b639afd04e0ef6b280af3c/src/lib.rs#L427-L438 

For the struct field it's easier to keep the `cfg` list small, but technically that should have the same long list as with the public version.

@MortronMeymo you will to make a pr for this? At least to add Android, you can keep the struct field alone if you mainly care about Android.

**Comment by MortronMeymo** [comment]
@Thomasdezeeuw I added PR #338 to fix the setters and decided to leave the field alone but make it so that if the sys crate supports setting the values than the setters on the TcpKeepAlive struct are also available.

**Comment by MortronMeymo** [comment]
@Thomasdezeeuw sooo any chance this will be available as a 0.4.x on crates.io? We currently can only pull dependencies from there... :see_no_evil:

**Comment by Thomasdezeeuw** [comment]
Then we'll have to backport it to the v0.4.x branch

**Comment by MortronMeymo** [comment]
If you want I can prepare a CR for that as well, but what is the strategy for backporting? Should I just cherry-pick my commit to that branch or how do you usually do it?

**Comment by Thomasdezeeuw** [comment]
Yes cherry-pick is the way to go and just target `v0.4.x` in your pr.

**Comment by MortronMeymo** [comment]
@Thomasdezeeuw thanks for the quick `0.4.6` release :D
