### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by Wodann** [rust-lang/socket2#34]
I have been working on a [cross-platform Bluetooth implementation](https://github.com/wodann/io-bluetooth-rs), and have my own cross-platform Socket implementation that is very similar to yours. To reduce duplicity, I'd like to add Bluetooth support to your repository, and use it as a dependency.

**Comment by Wodann** [comment]
@alexcrichton  If I'd create a pull request that implements Bluetooth support, would you be willing to add it to your repository, or would you rather keep it as a net-only socket repository?

**Comment by alexcrichton** [comment]
If it's small enough and pretty cross platform, makes sense to me! If it's very platform specific though and/or a pretty big extension, it may be best as a separate crate.

**Comment by Thomasdezeeuw** [comment]
@Wodann do you still want to merge this with socket2? Or do you think it's best to continue living in its own crate?

**Comment by Wodann** [comment]
I've honestly not had time to finish the conversion, since I originally started on it. As such, feel free to close the issue.
