### ISSUE TITLE
Query nonblocking status

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/socket2#347]
I'd like to know whether a given socket is in O_NONBLOCK mode or not (for debugging purposes). Most methods on `Socket` have a getter and a setter, but for `set_nonblocking` I cannot find the corresponding `nonblocking` getter that I would need for that.

**Comment by Thomasdezeeuw** [comment]
I don't know if it's possible to get this status on Windows, maybe using [`WSAIoctl`](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaioctl)?
