### ISSUE TITLE
error[E0583]: file not found for module `sys`

### ISSUE THREAD

**Issue by justinmchase** [rust-lang/socket2#35]
I'm trying to build using `wasm-pack build` and its giving me this error:
```
    Compiling socket2 v0.3.9

error[E0583]: file not found for module `sys`
  --> /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.9/src/lib.rs:72:5
   |
72 | mod sys;
   |     ^^^
   |
   = help: name the file either sys.rs or sys/mod.rs inside the directory "/home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.9/src"
```

I'm very new at this but it seems like its pulling down the latest version of the code in this repo and failing to compile. 

Any help would be greatly appreciated.

**Comment by justinmchase** [comment]
This line appears to vary from master:
https://github.com/alexcrichton/socket2-rs/blob/ca89d63b87f4ec62f059caa1d9379c0dc8f1cd2b/src/lib.rs#L72

When I do a simple cfg check in my own app it appears to be resolved as "unix" so I'm not sure why this is failing.

Any workarounds welcome.

**Comment by alexcrichton** [comment]
Thanks for the report! This crate needs to add some stubs for the wasm target that all return errors, but otherwise shouldn't be too hard to add.

**Comment by murtyjones** [comment]
I'm getting this error too in a project of my own, and it's kind of mysterious because it seemed to come out of nowhere and when I run `wasm-pack build` in other projects, it works.

[this person](https://github.com/alexcrichton/socket2-rs/issues/28#issuecomment-423444700) seems to have found a workaround but I couldn't figure out what it was.

**Comment by justinmchase** [comment]
I was not able to other than to not use the library that depended on this. I looked at it for a while and I bet there is a way but I'm not familiar enough with Rust to figure it out yet.

For what it's worth I was using WSL on windows but after a bunch of tests it seems like Rust correctly interprets it as unix and there wasn't a problem with the conditional compilation macros in smaller independent tests.

**Comment by thomasnz** [comment]
I think I am getting a similar error. I'm using a library that depends on socket for a WASM project.

`error[E0432]: unresolved import crate::sys --> C:\Users\Thomas\.cargo\registry\src\github.com-1ecc6299db9ec823\socket2-0.3.12\src\socket.rs:23:5`
`   |`
`23 | use crate::sys;`
`   |     ^^^^^^^^^^ no sys in the root`

**Comment by twitchax** [comment]
As far as I can tell, this is still an issue.  `socket2` fails to compile on wasm becaause the `sys` module is only imported for a `unix` or `windows` target.

**Comment by Thomasdezeeuw** [comment]
@twitchax that's because wasm isn't supported.

**Comment by twitchax** [comment]
@Thomasdezeeuw, I was mostly commenting because this issue was closed without explanation.  That would have been a helpful note to people who come across this issue. :)

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw, I was mostly commenting because this issue was closed without explanation. That would have been a helpful note to people who come across this issue. :)

To be fair the issuer closed it, not the maintainers but I understand. We should probably add a `compile_error` for unsupported targets to make it clear from the error message.

**Comment by justinmchase** [comment]
Sorry, I think I just closed it because I didn't want to see it in my list of open issues anymore and nobody seemed to care about it.

**Comment by twitchax** [comment]
@justinmchase, haha, no problem.

I think it is still something that would be nice.  There are a lot of projects that rely on `socket2` that cannot be used in `wasm` targets due to the lack of support here.  For example, I am testing how feasible it would be to use a project like `warp` or `rocket` in Rust-based CloudFlare Workers.

**Comment by damirka** [comment]
Can confirm that it is an issue for some (if not many) people. I wonder if there is a way to nicely disable or put a placeholder for unsupported targets, so this functionality is disabled, but not blocking compilation of other crates. 🤔

**Comment by Thomasdezeeuw** [comment]
I'm closing this in favour of https://github.com/rust-lang/socket2/issues/268 to track wasm support.

**Comment by Neo-Ciber94** [comment]
As say adobe you need to disable or exclude dependencies that does not target wasm32 which is what trunk target.

Foe example can exclude them this way:

```rs
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.57"
actix-web = "4"
stdweb = "0.4.20"
```

**Comment by PDFergus** [comment]
> @justinmchase, haha, no problem.
> 
> I think it is still something that would be nice. There are a lot of projects that rely on `socket2` that cannot be used in `wasm` targets due to the lack of support here. For example, I am testing how feasible it would be to use a project like `warp` or `rocket` in Rust-based CloudFlare Workers.

Yeah I just found out by nasty Surprise after integrating my Database calls to the front end only to find out that although the queries are crafted correctly that the database structure I am using may in fact use Socket2 nested deep down in its dependency structure, specifically in the aws_auth_sdk.  So if you are using any data from an amazon authenticated source, you may be at the migration point.

oh well back to the drawing board I guess. Maybe I will give SurealDB a shot.

**Comment by NazarKhlopeniuk** [comment]
I have the same issue.
How can I handle this?

**Comment by Thomasdezeeuw** [comment]
> I have the same issue. How can I handle this?

@NazarKhlopeniuk what platform are you using? If you're using wasm you can help in https://github.com/rust-lang/socket2/issues/268.

**Comment by NazarKhlopeniuk** [comment]
windows 10 64bit.

**Comment by NazarKhlopeniuk** [comment]
This is the error that I get after running "cargo test"

**Comment by Thomasdezeeuw** [comment]
Please don't post text as a image, you can put multiple lines line that between "```" to create a code block, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

The error shown in image seems related to wasm/axum, not Socket2. But if you're pulling in socket2 I'm sorry to say that it won't work for now as we don't support wasm, see https://github.com/rust-lang/socket2/issues/268.

**Comment by Tahmid-Hossen** [comment]
I am getting this error while run wasm-pack build. Anyone assist me to fix it

[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling wasm-bindgen-backend v0.2.92
   Compiling serde_derive v1.0.197
   Compiling inout v0.1.3
   Compiling cipher v0.3.0
   Compiling url v2.5.0
   Compiling sha1_smol v1.0.0
   Compiling socket2 v0.4.10
   Compiling base64 v0.20.0
error[E0583]: file not found for module `sys`
   --> C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\sys.rs" or "C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\sys\mod.rs"
    = note: if there is a `mod sys` elsewhere in the crate already, import it with `use crate::...` instead

error: Socket2 doesn't support the compile target
   --> C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\lib.rs:127:1
    |
127 | compile_error!("Socket2 doesn't support the compile target");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved imports `crate::sys::sa_family_t`, `crate::sys::sockaddr`, `crate::sys::sockaddr_in`, `crate::sys::sockaddr_in6`, `crate::sys::sockaddr_storage`, `crate::sys::socklen_t`, `crate::sys::AF_INET`, `crate::sys::AF_INET6`
 --> C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\sockaddr.rs:6:5
  |
6 |     sa_family_t, sockaddr, sockaddr_in, sockaddr_in6, sockaddr_storage, socklen_t, AF_INET,
  |     ^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^ no `AF_INET` in `sys`
  |     |            |         |            |             |                 |
  |     |            |         |            |             |                 no `socklen_t` in `sys`
  |     |            |         |            |             no `sockaddr_storage` in `sys`
  |     |            |         |            no `sockaddr_in6` in `sys`
  |     |            |         no `sockaddr_in` in `sys`
  |     |            no `sockaddr` in `sys`
  |     no `sa_family_t` in `sys`
7 |     AF_INET6,
  |     ^^^^^^^^ no `AF_INET6` in `sys`
  |
  = help: consider importing this module instead:
          crate::sockaddr

error[E0432]: unresolved imports `crate::sys::c_int`, `crate::sys::getsockopt`, `crate::sys::setsockopt`, `crate::sys::Bool`
  --> C:\Users\aryan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\socket2-0.4.10\src\socket.rs:23:24
   |
23 | use crate::sys::{self, c_int, getsockopt, setsockopt, Bool};

**Comment by Thomasdezeeuw** [comment]
@Tahmid-Hossen WASM is not supported, see https://github.com/rust-lang/socket2/issues/268.
