### ISSUE TITLE
Accept unix abstract namespace paths starting with @

### ISSUE THREAD

**Issue by GeorgeLS** [rust-lang/socket2#353]
Hello there,

I was writing some unix specific code using your library (thanks for this library by the way) and I came across this "issue".
Many libraries support specifying abstract namespace paths by prepending the path with the '@' character.
This is pretty common in Unix and convenient as well since it's not convenient to format paths or add the null character (\0) at the start of the path so '@' is used instead.

However, since this was not handled explicitly in the Unix code I thought of adding this functionality.

I would say this is more of a quality of life improvement rather than a feature since the library already supports abstract namespace paths.

**Comment by Thomasdezeeuw** [comment]
Hmm... I'm not sure about this. Generally speaking we prefer not to modify any parameters and just provide a thin, safe layer on top of the API provided by the OS/libc.

**Comment by GeorgeLS** [comment]
Yeah, you are right. I looked into the kernel code and it doesn't explicitly handle this. It is a convention handled by either application code or other libraries. Since this is a thin OS layer, this should probably be handled in the application code.

Thanks for the response. Closing this issue now.
