### ISSUE TITLE
Some API not showing up on docs

### ISSUE THREAD

**Issue by ibigbug** [rust-lang/socket2#355]
for example https://github.com/rust-lang/socket2/blob/ff79dee5174b8beb32b54e35636fc45358e2d705/src/sys/unix.rs#L1586

doesn't seem to exist here https://docs.rs/socket2/0.4.7/socket2/struct.Socket.html

is it intentional?

**Comment by Thomasdezeeuw** [comment]
This is because it's Apple only. If you look at e.g. the Darwin docs.rs: https://docs.rs/socket2/0.4.7/x86_64-apple-darwin/socket2/struct.Socket.html#method.bind_device_by_index, it's present.

**Comment by ibigbug** [comment]
thank you!

 but how do to switch to the "Apple" version or check what versions there are? is it some rust doc feature or this doc is built that way.

**Comment by Thomasdezeeuw** [comment]
In the bar at the top you can select the platform for the documentation. See the attached screenshot.

![Screenshot 2022-10-09 at 23 01 25](https://user-images.githubusercontent.com/3159064/194779376-54823660-d4eb-4377-ac02-14e4cdd9f6ab.png)
