### ISSUE TITLE
UDPLITE support

### ISSUE THREAD

**Issue by dtaht** [rust-lang/socket2#361]
Somewhat related to #350 is UDPLITE. It's supported on many an OS (linux and bsd for sure), and by default behaves just like UDP, with the exception that you can shorten the checksum, which is increasingly not terribly useful for its intended purpose, but it's there...

I'm getting kind of concerned  about UDP getting so heavily used by QUIC, limited port space from CGNATs, etc, and it's always seemed to me that at least trying to make udplite work was rather straightforward, and only a couple lines of code.

https://en.wikipedia.org/wiki/UDP-Lite

**Comment by Thomasdezeeuw** [comment]
Prs would be welcome.

**Comment by dtaht** [comment]
Noted. Whenever I get better at rust.

**Comment by Thomasdezeeuw** [comment]
@dtaht you can take a look at https://github.com/rust-lang/socket2/pull/359 and try to copy and modify it for UDPLITE.

**Comment by dtaht** [comment]
It is even simpler than that. This is all there is to it, in C:

       sockfd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDPLITE);
