### ISSUE TITLE
Support IPV6_TCLASS

### ISSUE THREAD

**Issue by duskmoon314** [rust-lang/socket2#363]
`IPV6_TCLASS` is `IP_TOS` in IPv6. It is already defined in `libc` ([ref](https://docs.rs/libc/0.2.138/libc/constant.IPV6_TCLASS.html)).

A simple solution would be `pub(crate) use libc::IPV6_TCLASS;`. But I'm not sure how to correctly configure the cfg attribute.

**Comment by Thomasdezeeuw** [comment]
Here is an example setting function: https://github.com/rust-lang/socket2/blob/05ca98999bf63722e8c5f6eb2a89d2c42aa16730/src/sys/unix.rs#L1776-L1790

An example getter: https://github.com/rust-lang/socket2/blob/05ca98999bf63722e8c5f6eb2a89d2c42aa16730/src/sys/unix.rs#L1739-L1744

Basically replace `IPV6_FREEBIND` with `IPV6_TCLASS` and give it a good name.

**Comment by duskmoon314** [comment]
@Thomasdezeeuw `TCLASS` is also defined in `windows-sys`, so I think it may be correct to follow the impl of `IP_TOS`. I just wonder how to know whether an OS supports it. 

```rust
#[cfg(not(any(
    target_os = "fuchsia",
    target_os = "redox",
    target_os = "solaris",
    target_os = "illumos",
)))]
pub(crate) use libc::IP_TOS;
#[cfg(
    // TODO: How to fill this?
)]
pub(crate) use libc::IPV6_TCLASS;
```

**Comment by duskmoon314** [comment]
I just opened a PR trying to solve this issue. If anyone is familiar with these options, please review it.
