### ISSUE TITLE
Implement `std::cmp::Eq` and `std::hash::Hash` for `socket2::SockAddr`, so it can be used as a key in `std::collections::HashMap`

### ISSUE THREAD

**Issue by lshlyapnikov** [rust-lang/socket2#372]

**Comment by Thomasdezeeuw** [comment]
I'm not sure about `Hash`, but I think we can implement `Eq`. But do note that `SockAddr` is quite big, if you're using just IP address you're better of using `std::net::SocketAddr`.

**Comment by lshlyapnikov** [comment]
@Thomasdezeeuw you mean it is not possible or are there any other reasons?

My use case is tracking UDP packet sequence numbers per sender (`socket2::SockAddr`).
I use `recv_from` which gives me the `SockAddr` of the sender.
```
pub fn recv_from(&self, buf: &mut [MaybeUninit<u8>]) -> io::Result<(usize, SockAddr)>
```
and a `HashMap` to keep expected sequence numbers per sender.

I currently have to implement a newtype that wraps around `socket2::SockAddr` and implement `PartialEq` and `Hash` for it.

I guess can I can open a pull request. Let me know.

**Comment by lshlyapnikov** [comment]
you know... it is actually for IP address only and `std::net::SocketAddr` has `Hash` and `Eq` implemented. I could use ``std::net::SocketAddr` as a key in `HashMap`.  However converting from `socket2::SockAddr` to `std::net::SocketAddr` is not free and I don't want to do this for every UDP packet I receive.
```
pub fn as_socket(&self) -> Option<SocketAddr> {
```

**Comment by Thomasdezeeuw** [comment]
> It is actually for IP address only and `std::net::SocketAddr` has `Hash` and `Eq` implemented. I could use `std::net::SocketAddr` as a key in `HashMap`. However converting from `socket2::SockAddr` to `std::net::SocketAddr` is not free and I don't want to do this for every UDP packet I receive.
> 
> ```
> pub fn as_socket(&self) -> Option<SocketAddr>
> ```

Using `std::net::SocketAddr` reduce the memory usage, so I think it would worth benchmarking both. The conversion to and from `socket2::SockAddr` isn't too costly I think.

But a pr to implement it would be welcome.

**Comment by lshlyapnikov** [comment]
See #373. I will ping you when it is ready for review.
