### ISSUE TITLE
Socket::shutdown() does not work reliably!

### ISSUE THREAD

**Issue by dEajL3kA** [rust-lang/socket2#377]
Hello.

Function `Socket::shutdown()` is supposed to:
> This function will cause all pending and future I/O on the specified portions to return immediately with an appropriate value.

However, I found that this does **not** work. The pending `accept()` will block forever, even after `shutdown()` has been invoked, with **no** way to cleanly shut down the application. Here is a minimal example to illustrate the problem:

```rust
use socket2::{Socket, SockAddr, Domain, Type};
use std::net::{SocketAddr, Shutdown};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::thread;
use std::time::Duration;

fn main() {
    let socket_addr = SocketAddr::new("127.0.0.1".parse().unwrap(), 8088);
    let socket = Arc::new(Socket::new(Domain::for_address(socket_addr), Type::STREAM, None).unwrap());
    socket.bind(&SockAddr::from(socket_addr)).unwrap();
    socket.listen(512).unwrap();

    let stop = Arc::new(AtomicBool::new(false));
    let thread_stop = stop.clone();
    let thread_socket = Arc::clone(&socket);

    let thread_handle = thread::spawn(move || {
        println!("Thread started!");
        while !thread_stop.load(Ordering::Acquire) {
            println!("Waiting for an incoming connection...");
            match thread_socket.accept() {
                Ok((_stream, _addr)) => println!("Connection was accepted!"),
                Err(err) => println!("Failed to establish the connection: {}", err),
            }
        }
        println!("Thread is exiting!");
    });

    thread::sleep(Duration::from_secs(10));

    println!("Initiating shutdown!");
    stop.store(true, Ordering::Release);
    socket.shutdown(Shutdown::Both).ok(); // <-- Force socket to shut down ASAP !!!

    println!("Waiting for thread to exit...");
    thread_handle.join().ok();

    println!("Thread has exited. Goodbye!");
}
```

Basically, the thread hangs forever, unless we are lucky and an actual connection happens to come in :smirk:

There is **no** way to cleanly shut down, as far as I can tell...

Tested with `socket2` v0.4.7 and Rust v1.68.0 on Windows 10 x64 fully patched.

Best regards!

**Comment by Thomasdezeeuw** [comment]
Please read the manual of `shutdown(2)` on your OS. `shutdown` doesn't work for the equivalent of a `TcpListener` (that's why it's not implemented for `std::net::TcpListener`), only for the equivalent of `TcpStream`.
