### ISSUE TITLE
Please provide any facility to shut down a listening Socket

### ISSUE THREAD

**Issue by dEajL3kA** [rust-lang/socket2#378]
Suppose we have an application that actually uses `socket2::Socket` to handle incoming connections:
```
let socket = Socket::new(Domain::for_address(socket_addr), Type::STREAM, None).unwrap();
socket.bind(&SockAddr::from(socket_addr)).unwrap();
socket.set_read_timeout(Some(Duration::from_secs(10))).unwrap();
socket.listen(256).unwrap();

while !stopping {
	let connection = socket.accept();
	match connection {
		Ok((stream, addr)) => process_request(stream, addr),
		Err(err) => error!("Failed to establish the connection: {}", err),
	}
}
```

**Feature request:** Please provide ***any*** facility to orderly shut down the application.

This is a standard use-case that will pop up in *any* application that uses `socket2::Socket` to handle incoming connections.

At the moment, to the best of my understanding, there is **no** way to orderly shut down the listener, as `accept()` will be blocked for an **undefined** amount of time. It will essentially block *forever*, unless a new connection request happens to come in – which, of course, we do **not** want to depend on. Furthermore, there is **no** way to either specify a **timeout** for `accept()`, nor is there a method to "stop" the socket from listening, which we could call from another thread or from the ctrl+c handler. The `Socket::shutdown()` function, which looks like a great candidate, also does **not** work for this, apparently.

(Note: Setting the socket to *non-blocking* mode, so that `accept()` never blocks at all, is **not** a solution either, as it would require the listener to implement "spinning", which is an enormous waste of CPU cycles and therefore is a no-go in practice)

So, please either make it possible to specify a timeout for `accept()`, or add a method to cleanly "stop" the listening socket.

Thank you and best regards!

--------

For reference, Java's `ServerSocket` has this feature ever since:
https://docs.oracle.com/javase/8/docs/api/java/net/ServerSocket.html#setSoTimeout-int-

**Comment by Thomasdezeeuw** [comment]
What you're asking for doesn't exist. Socket2 provides a safe wrapper around the OS interface, nothing more.

One thing that might work is to make a copy of the fd and close that from another thread. But you have to be careful with `Socket2` closing it's own fd after that.

**Comment by dEajL3kA** [comment]
But how is it "safe" if we can't even orderly shut down the application?

The possible deadlock, which currently cannot really be avoided, should be considered a problem, I think.

I mean, really, how is it supposed to be used in real-world application, if we can never cleanly shut down?

Thank you!

**Comment by the8472** [comment]
> (Note: Setting the socket to non-blocking mode, so that accept() never blocks at all, is not a solution either, as it would require the listener to implement "spinning", which is an enormous waste of CPU cycles and therefore is a no-go in practice)

You can use polling, e.g. via [mio::Poll](https://docs.rs/mio/latest/x86_64-unknown-linux-gnu/mio/struct.Poll.html)

**Comment by Thomasdezeeuw** [comment]
> But how is it "safe" if we can't even orderly shut down the application?

Well we can, but we have to use non-blocking accept.

> The possible deadlock, which currently cannot really be avoided, should be considered a problem, I think.

What deadlock are you talking about?

> I mean, really, how is it supposed to be used in real-world application, if we can never cleanly shut down?

As @the8472 pointed out you can non-blocking I/O, possibly by using Mio. Shutting down a listening socket it's an easy problem to solve, though their are multiple solution to it. But as far as I know they all require non-blocking accept calls (which socket2 can also do, if you don't want to use Mio). For example you could do something like `connect_timeout`: https://github.com/rust-lang/socket2/blob/35ee2ff996d5bfb91235a6994a05435b2ac8fa80/src/socket.rs#L224-L238 
However it will incur a bit of a performance penalty as it requires multiple system calls, not just 1.

**Comment by dEajL3kA** [comment]
> What deadlock are you talking about?

There is guarantee that `socket2::accept()` or `std::net::TcpListener` returns **_ever_**, or in any timely manner.

We can neither set a timeout, nor force the port to stop listening (aborting the pending `accept()` calls) from other thread.

**Comment by dEajL3kA** [comment]
> You can exit the application from another thread without unblocking the accept call.

Sure. But "killing" a thread without a proper `join()` is the definition of "unsafe" and not what we really want 😨 

By the point in time we shut down the application, the "listener" thread **_might_** be blocked in `accept()` call, but it also might be in the middle of something else (e.g. writing out a file) just as well...

**Comment by the8472** [comment]
> Sure. But "killing" a thread without a proper join() is the definition of "unsafe" 

No, calling [process::exit](https://doc.rust-lang.org/std/process/fn.exit.html) is not unsafe.

**Comment by dEajL3kA** [comment]
> No, calling [process::exit](https://doc.rust-lang.org/std/process/fn.exit.html) is not unsafe.

Isn't that the definition of "unsafe"? 🤔 

> This function will never return and will **immediately** terminate the current process. The exit code is passed through to the underlying OS and will be available for consumption by another process.
> 
> Note that because this function never returns, and that it terminates the process, **_no destructors on the current stack or any other thread’s stack will be run_**. If a clean shutdown is needed it is recommended to only call this function at a known point where there are no more destructors left to run; or, preferably, simply return a type implementing [Termination](https://doc.rust-lang.org/std/process/trait.Termination.html) (such as [ExitCode](https://doc.rust-lang.org/std/process/struct.ExitCode.html) or Result) from the main function and avoid this function altogether:

**Comment by Thomasdezeeuw** [comment]
> > What deadlock are you talking about?
> 
> There is **no** guarantee that `socket2::accept()` or `std::net::TcpListener` returns **_ever_**, or in any timely manner.

That's true for nearly any system call with with sockets. For example a recv/read call can also wait for ever if the peer keep the connection open, but doesn't actually sends any data.

> We can neither set a timeout, nor force the port to stop listening (aborting the pending `accept()` calls) from other thread.

You can interrupt the system call by sending yourself a process signal, or as we've said above use non-blocking I/O.

> > You can use polling, e.g. via [mio::Poll](https://docs.rs/mio/latest/x86_64-unknown-linux-gnu/mio/struct.Poll.html)
> 
> Thanks! I know there's a bunch of alternative I/O library. And I will probably give `mio` a try now.
> 
> Still, if we can't handle a very basic "standard" use case with `std::net` or `socket2` it feels kind of incomplete/broken 🤔

To me it seems that you're new to network programming, that's fine we all start somewhere, but I think it would be worth your time to learn more about networking, for example by reading [Beej's Guide to Network Programming](https://beej.us/guide/bgnet/).

**Comment by dEajL3kA** [comment]
> That's true for nearly any system call with with sockets. For example a recv/read call can also wait for ever if the peer keep the connection open, but doesn't actually sends any data.

That's why we have `read_timeout()` and `write_timeout()` :smirk:

It's just that, _in Rust_ (`std::net` or `socket2`), the equivalent `accept_timeout()` is lacking...

> You can interrupt the system call by sending yourself a process signal, or as we've said above use non-blocking I/O.

Can you give a minimal example how to do this in Rust?

> To me it seems that you're new to network programming

Quite the opposite! Just new to Rust 😄 

In other languages I have used, such as Java, the very basic "standard" uses-case of requiring an `accept()` operation on the `ServerSocket` to have a **proper timeout** can be accomplished swiftly with Standard Library facilities.

So I'm a bit surprised that a "modern" language like Rust falls short here, requiring either to use an alternative I/O library – which isn't really an excuse for an obvious shortcoming in the `std::net` library – or falling back to low-level OS system calls.

**Comment by Thomasdezeeuw** [comment]
> That's why we have `read_timeout()` and `write_timeout()` 😏
>
> It's just that, _in Rust_ (`std::net` or `socket2`), the equivalent `accept_timeout()` appears to be lacking... ❓

Again, that's a socket option provided by the OS. There is no such option for the `accept` system call, nor for the `connect` call for example.

> > You can interrupt the system call by sending yourself a process signal, or as we've said above use non-blocking I/O.
> 
> Can you please give a minimal example how to do this in Rust?

`libc::kill(std::process::id(), libc::SIGINT);`, but you have to setup a process signal handler to not kill your own process.

> > To me it seems that you're new to network programming
> 
> Quite the opposite! Just new to Rust 😄

I didn't say you're new to programming, just new to *network* programming. 

> In other languages I have used a lot, such as Java, the very basic "standard" uses-case of requiring an `accept()` operation on the `ServerSocket` to have a **proper timeout** can be accomplished swiftly with Standard Library facilities: https://docs.oracle.com/javase/8/docs/api/java/net/ServerSocket.html#setSoTimeout-int-
> 
> Just for reference, Python has it too: https://stackoverflow.com/a/41643863
> 
> So I'm a bit surprised that a "modern" language like Rust falls short here, requiring either to use an alternative I/O library – which isn't really an excuse for an obvious shortcoming in the `std::net` library – or falling back to low-level OS system calls.

This has nothing to the with the language. Socket2 provide a wrapper around system calls, nothing more. As per our documentation:

> This crate provides as direct as possible access to the system’s functionality for sockets, this means little effort to provide cross-platform utilities. It is up to the user to know how to use sockets when using this crate.* If you don’t know how to create a socket using libc/system calls then this crate is not for you*. 

I think you should look into Tokio, it provided higher level APIs such as the ones you mentioned in Java and Python. The socket2 library is low-level, just providing wrappers around OS system calls. If the OS doesn't provide it, like what your asking for now, socket2 doesn't provide it.

> I mean, it's very close to giving you everything that is required, but then one important piece is missing...
> 
> (Note: Because I'm new to Rust, I don't know whether I'm just missing something obvious or whether it is really missing 😅 )

Yes, you're missing something obvious. The libraries you're referring to in Java and Python use multiple system calls, socket2 does not. It provides functions to use the system calls, that's it.

**Comment by dEajL3kA** [comment]
Why has this been close ???

I'm still waiting to see an example code, in Rust, how to original Problem pointed out in the first post can be solved!

And I mean with pure Rust and ´socket2::Socket´ 😏 

> Yes, you're missing something obvious. The libraries you're referring to in Java and Python use multiple system calls, socket2 does not. It provides functions to use the system calls, that's it.

Then please give an actual example that shows how the "standard" functionality available in Java, Python and many others can be accomplished with the functions exposed by ´socket2::Socket´.

If you can't show this, then poisonously ´socket2::Socket´ is lacking and the feature request is very legitimate!

**Comment by Thomasdezeeuw** [comment]
> Why has this been closed ???
> 
> I'm still waiting to see an example code, in Rust, how to original Problem pointed out in the first post can be solved !!!

Let me be very clear. **This not a help desk**. You are free to ask questions, but you can't expect an answer. I don't work for you.

I've stated this before and it will be last time. Socket2 doesn't provide what your asking because the OS doesn't provide it. So, socket2 will not support your use case.
