### ISSUE TITLE
Windows 11 Err(Os { code: 10022, kind: InvalidInput, message: "An invalid argument was supplied." }) recv_from

### ISSUE THREAD

**Issue by ns-blee** [rust-lang/socket2#388]
same issue as here https://github.com/libpnet/libpnet/issues/453

any workaround or idea? 

Im using a send and receive socket. Receive is the one that errs. Works on linux && macos.

**Comment by Thomasdezeeuw** [comment]
Can you share what you're doing? For example some code?

**Comment by ns-blee** [comment]
Something like this.. but I cant even use Type to test the min example.. any idea why? It works fine in the actual project but not here... 

```
use socket2::{Domain, Protocol, SockAddr, Socket, Type};
use std::mem::MaybeUninit;
use std::net::SocketAddr;
fn main() -> std::io::Result<()> {
    let socket_type = Type::RAW;

    let receive = Socket::new(Domain::IPV4, socket_type, Some(Protocol::ICMPV4))?;
    let send = Socket::new(Domain::IPV4, socket_type, Some(Protocol::ICMPV4))?;

    send.send_to(
        &[0u8; 64],
        &SockAddr::from(SocketAddr::new([8, 8, 8, 8].into(), 0)),
    )
    .unwrap();

    let mut buf = [MaybeUninit::<u8>::uninit(); 64];

    receive.recv_from(&mut buf).unwrap();

    println!("{:?}", receive);

    Ok(())
}
```

**Comment by ns-blee** [comment]
Im building a simple trace app. 

I tried binding both sockets to the same address which takes care of the error... but I get nothing back... 

what am I missing here?

**Comment by Thomasdezeeuw** [comment]
You can't send to port `0`, in the line `&SockAddr::from(SocketAddr::new([8, 8, 8, 8].into(), 0))`.

**Comment by ns-blee** [comment]
is this a windows specific problem? because using 0 on mac or linux works fine

**Comment by ns-blee** [comment]
The real problem here is the sockets do not work the same way across all 3 platforms, though claim to.

If an ICMP socket requires a port # in windows thats a bug IMO as ports arent really a thing in ICMP. 

The other problem is I can receive on a socket in macos and linux without calling bind directly. Calling recv_from yields "An invalid argument was supplied" in windows but not in linux or macos when bind is not called directly...

**Comment by Thomasdezeeuw** [comment]
> is this a windows specific problem? because using 0 on mac or linux works fine

I don't know. I don't use ICMP often, at least I don't program it.

> The real problem here is the API does not work the same way across all 3 platforms.
> 
> If an ICMP socket requires a port # in windows thats a bug IMO, and needs to be handled under the API, or documented as ports arent really a thing in ICMP.
> 
> The other problem is I can receive on a socket in macos and linux without calling bind directly. Calling recv_from yields "An invalid argument was supplied" in windows but not in linux or macos when bind is not called directly...

Socket2 doesn't really provide too much in term of cross platform support. We just expose the libc/windows-sys functions in a (slightly) safer/ergonomic way. It still requires OS specific knowledge is many cases. I'm afraid the API surface of Socket2 is too large to document *all* platform differences.

**Comment by ns-blee** [comment]
problem was 2 fold 1) need to bind to 0.0.0.0:0 in win 2) checksum. It appears windows has some enforcement mechanism over raw sockets....

**Comment by Thomasdezeeuw** [comment]
@ns-blee can this be closed?

**Comment by ns-blee** [comment]
Yes, thank you for your help.
