### ISSUE TITLE
0.5 doc page not published

### ISSUE THREAD

**Issue by atouchet** [rust-lang/socket2#397]
https://docs.rs/socket2/0.5.0/socket2/index.html

"The requested version does not exist"

Is there something going wrong here?

**Comment by notgull** [comment]
It takes a minute for `docs.rs` to update with the latest docs after a release.

**Comment by atouchet** [comment]
Ah, I see it's a few hours behind the latest crates being published.

**Comment by Thomasdezeeuw** [comment]
This is not something we control, we just publish to https://crates.io and docs.rs will pick up automatically. The docs should be ready by tomorrow.

**Comment by Darksonn** [comment]
Unfortunately, the docs.rs build has failed: https://docs.rs/crate/socket2/latest

**Comment by Thomasdezeeuw** [comment]
Log is here https://docs.rs/crate/socket2/0.5.0/builds/752625, I'll look into it tomorrow.
