### ISSUE TITLE
Suggestion: add method to get owned address from `SockAddr`.

### ISSUE THREAD

**Issue by t4lz** [rust-lang/socket2#412]
In https://github.com/metalbear-co/mirrord we need to send over the network a socket address that could either be an IP address, or an address of a unix socket. For that we would implement some enum like
```Rust
enum Address {
    Ip(SocketAddr),
    Unix(UnixAddress),
    ...
}

enum UnixAddress {
    Pathname(PathBuf),
    Abstract(Vec<i8>),
    Unnamed
}
```
(Or those types could all be present directly under the `Address` enum, that's a detail)

If you think this would be better, we could implement it in this crate instead of in our repo, something like `sock_addr.to_owned()` or whatever.

Should this be implemented here?

**Comment by Thomasdezeeuw** [comment]
You can already implement this by matching on [`SockAddr::family`](https://docs.rs/socket2/latest/socket2/struct.SockAddr.html#method.family) and then using the `SocketAddr::as_*` methods. I'm not convinced this needs to live in the socket2 crate.
