### ISSUE TITLE
Support for x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by DariuszOstolski** [rust-lang/socket2#416]
Hi,

It seems that since 0.5.x x86_64-unknown-linux-musl is no longer supported. Currently it doesn't compile due to  libc::DCCP_SOCKOPT_SERVICE usage which seems is not exported from muslc. I'm wondering if creating a PR to add target based on musl library would be beneficial for the community?

BR,
Dariusz

**Comment by Darksonn** [comment]
This is a duplicate of #405.
