### ISSUE TITLE
RFC 4607

### ISSUE THREAD

**Issue by godsey** [rust-lang/socket2#42]
Would it be possible to add support for Source Specific Multicast?

**Comment by alexcrichton** [comment]
Sure! PRs to add new bindings are always welcome!

**Comment by godsey** [comment]
Could you point me in the right direction for building with a locally modified libc binding? Pointing cargo to my cloned repo doesn’t seem to work, or I am doing it wrong.

**Comment by alexcrichton** [comment]
I'd recommend reading https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#overriding-dependencies for that

**Comment by fatpelt** [comment]
I actually just submitted a draft rfc for this.  pr #45

**Comment by Thomasdezeeuw** [comment]
Seems like this hasn't made any progress so I'm closing. More discussion and prs and still welcome of course.
