### ISSUE TITLE
TcpKeepalive::with_retries() doesn't seem to load and can't be used.

### ISSUE THREAD

**Issue by haddow777** [rust-lang/socket2#435]
Hello. I'm quite new to your crate. I am liking that it actually has keepalive functionality. Unfortunately, it doesn't seem to be working as described. I checked the docs and some example code. Here is how the example put it:

`let keepalive = TcpKeepalive::new().with_time(Duration::from_secs(4)).with_interval(Duration::from_secs(1)).with_retries(4);`

This is the error it gives:

> no method named `with_retries` found for struct `TcpKeepalive` in the current scope

The only problem with this is the compiler doesn't recognize with_retries() as being part of TcpKeepalive. I checked you documentation and it's there, clear as a bell. It does have OS specific targeting, but I am using it on a Debian server, which should be fine. I even checked the source and found it there. 

I'm not sure what the problem is. Maybe it's not detecting the OS as linux, I'm not sure.

**Comment by Thomasdezeeuw** [comment]
TCP keepalive is not available on all platforms, so it's behind the `all` feature. Did you try enabling that?

**Comment by haddow777** [comment]
Ah, thanks. still new to rust and didn't understand the feature system. 

I wonder, maybe a suggestion. I could see cases where people would like functionality like this in OSs that support it and remove it in ones that don't. As the method can be daisy chained, to have two versions to protect OSs that don't support it, you would have to duplicate all the calls. Could something like a flag parameter be possible? Like, for methods that face tighter restrictions, an additional bool parameter could be supplied. If false is passed, the method fires, but simply returns self instantly, otherwise if true is passed then the functionality does what it normally would. This way, the additional parameter is a signal that this method is different from others and requires special attention. At the same time, the programmer can do OS detection or whatever and set a flag for the call. this way, there only needs to be one daisy chained call as the method, no matter the flag, won't cause it to fail. It will simply have functionality or it won't. 

One aspect I like about a method like this is that each method requiring special attention flags your attention through an extra bool parameter. A feature flag likely changes things for a lot of calls, but i may only be focused on this one when I set the flag, but I may then accidentally use another restricted method and not know it's restricted unless I specifically look for it in the documentation.

Just a thought.

**Comment by Thomasdezeeuw** [comment]
> Ah, thanks. still new to rust and didn't understand the feature system.

If you haven't already, https://doc.rust-lang.org/cargo/reference/features.html is worth a read.

> I wonder, maybe a suggestion. I could see cases where people would like functionality like this in OSs that support it and remove it in ones that don't. As the method can be daisy chained, to have two versions to protect OSs that don't support it, you would have to duplicate all the calls.

What do you mean with duplicating the calls? You can use something like the following to make OS specific calls.

```rust
let keepalive = TcpKeepalive::new().with_time(Duration::from_secs(4)); // Options on all OSs.
#[cfg(target_os = "linux")]
let keepalive = keepalive.with_interval(Duration::from_secs(1)); // Linux only.
let keepalive = keepalive.with_retries(4); // More options for all OSs.
```

> Could something like a flag parameter be possible? Like, for methods that face tighter restrictions, an additional bool parameter could be supplied. If false is passed, the method fires, but simply returns self instantly, otherwise if true is passed then the functionality does what it normally would. This way, the additional parameter is a signal that this method is different from others and requires special attention. At the same time, the programmer can do OS detection or whatever and set a flag for the call. this way, there only needs to be one daisy chained call as the method, no matter the flag, won't cause it to fail. It will simply have functionality or it won't.

I don't want to pretend we support a certain call only to make it a no-op, it's just lying to the users (of this library) and it's not something I want to do. Furthermore the code might depend on the changed functionality that now doesn't work for *some* platforms, but it's not clearly indicated on what platforms it doesn't work.

> One aspect I like about a method like this is that each method requiring special attention flags your attention through an extra bool parameter. A feature flag likely changes things for a lot of calls, but i may only be focused on this one when I set the flag, but I may then accidentally use another restricted method and not know it's restricted unless I specifically look for it in the documentation.
> 
> Just a thought.

**Comment by Thomasdezeeuw** [comment]
Since the problems seems to be resolved I'm going to close, feel free to reopen or comment.
