### ISSUE TITLE
[Feature] Support getting SO_COOKIE socket option

### ISSUE THREAD

**Issue by bleggett** [rust-lang/socket2#436]
Linux (and related, I think Android as well) support the SO_COOKIE `getsockopt` flag (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5daab9db7b65df87da26fd8cfa695fb9546a1ddb) - this returns a kernel-managed `cookie` for a given socket, which is guaranteed to be unique per socket.

If there's no objection to add this to `socket2` as a `get` option, it should be simple enough to do.

**Comment by Thomasdezeeuw** [comment]
Fixed by https://github.com/rust-lang/socket2/pull/437.
