### ISSUE TITLE
 support target ohos

### ISSUE THREAD

**Issue by hlwqds** [rust-lang/socket2#451]
As target OpenHarmony was merged by rust, I hope socket2 can fit it too!
https://github.com/rust-lang/rust/pull/108792

![image](https://github.com/rust-lang/socket2/assets/50267463/dbf630a5-042c-46c5-99a4-7eabce375eb2)

**Comment by Thomasdezeeuw** [comment]
Pr to support it would be welcome, ideally with some kind of CI support. First you'll likely want to check that the `libc` crate has all the symbols we required.

**Comment by hlwqds** [comment]
> Pr to support it would be welcome, ideally with some kind of CI support. First you'll likely want to check that the `libc` crate has all the symbols we required.

Okay, let me try

**Comment by ldm0** [comment]
Fixed by #491

**Comment by Nugine** [comment]
#491 is deleted? The commit seems to be this one https://github.com/rust-lang/socket2/commit/d11936fbc9724595e0f810728a95311a76e614a5
