### ISSUE TITLE
nonblocking connect

### ISSUE THREAD

**Issue by dbregman** [rust-lang/socket2#466]
It would be very useful to have a way to do non-blocking connect. Socket2's existing code in connect_timeout()/poll_connect() already implements 99% of this. All that is needed is for body of the loop in poll_connect() to be exposed as a separate function that can be used to check if the connection has been established.

**Comment by Thomasdezeeuw** [comment]
I'm afraid socket2 isn't the library to do this in, a non-blocking connect isn't as simple as it seems see https://github.com/Thomasdezeeuw/heph/blob/5dbc14b32d12241e48d4afc022b8bc617f5a9ce8/rt/src/net/tcp/stream.rs#L562-L583 for some more information. You can try [Mio](https://docs.rs/mio/latest/mio/) for this (happen to have the same maintainer ;) )

**Comment by dbregman** [comment]
Hi @Thomasdezeeuw can you clarify? It seems to me that the code already implements nonblocking connect inside connect_timeout(), the functionality is just not exported in a reusable way.

**Comment by Thomasdezeeuw** [comment]
> Hi @Thomasdezeeuw can you clarify? It seems to me that the code already implements nonblocking connect inside connect_timeout(), the functionality is just not exported in a reusable way.

I reluctantly accepted `connect_timeout` back in https://github.com/rust-lang/socket2/issues/190 / https://github.com/rust-lang/socket2/pull/194. It's not the goals of socket2 to support non-blocking I/O, other libraries already exists for that and they do a good job at it. I know that because I maintain one. Supporting non-blocking connect isn't as easy as it seems when you want to give back control to the user. `connect_timeout` is simple because it can still block by calling `poll(2)`/`WSAPoll`, it's not really non-blocking.

**Comment by dbregman** [comment]
I'm not sure what you are getting at when you say "it isn't as simple as it seems". If the code in connect_timeout() works correctly then why shouldn't it be exposed to the user to allow checking for completion of the connection?

**Comment by Thomasdezeeuw** [comment]
I've stated this before and I'll state it for the last time: socket2 is not the place for non-blocking I/O.

Doing non-blocking I/O effectively is not easy. Socket2 however can help in doing non-blocking I/O as most socket related system calls are wrapped. You can call `socket.set_nonblocking(true)` and then do the `poll(2)` calls yourself. Or you can use another library for that. Socket2 isn't going to do it, it's simply out of scope for the library.

**Comment by dbregman** [comment]
You've stated 3 times that "it's not easy", but I don't understand what relevance this has. The supposedly difficult code is already written in the library and therefore the maintenance burden is already present?

Can you explain how it makes more sense for users to copy-paste the existing code out of the lib (for each platform) than simply providing a pub fn to the existing logic that is already being maintained? That is what I have already done BTW since I needed this right away, but it's obviously less than ideal for many reasons.
