### ISSUE TITLE
Set `ss_len` when creating `SockAddr` from std

### ISSUE THREAD

**Issue by Berrysoft** [rust-lang/socket2#468]
The `sockaddr_storage` type of BSD contains a field `ss_len` that represents the size of the sockaddr. When converting from `SocketAddr` etc., we need to set them correctly. Otherwise, it may report wrong result when comparing addresses.

**Comment by Thomasdezeeuw** [comment]
Maybe we can even drop `SockAddr::len` on targets that contain `ss_len`. A pr to fix the original issue and/or drop `SocketAddr::len` would be welcome.
