### ISSUE TITLE
Why cannot find WASStartup and WSACleanup in source code?

### ISSUE THREAD

**Issue by takkuumi** [rust-lang/socket2#472]
Question 1: I found that the WINDOWS system handles the network offline (unplug the peer network cable), and it takes about 8 seconds for the program to detect it.
Problem 2: During the brute force test, connections are constantly established and closed (shutdown). Socket2 does not call the WSACleanup function, so the connection fails.

**Comment by Thomasdezeeuw** [comment]
> Question 1: I found that the WINDOWS system handles the network offline (unplug the peer network cable), and it takes about 8 seconds for the program to detect it.

This is outside of the scope of socket2. Socket2 doesn't do anything to change this.

> Problem 2: During the brute force test, connections are constantly established and closed (shutdown). Socket2 does not call the WSACleanup function, so the connection fails.

We use the standard library for `WSAStartup`, see https://github.com/rust-lang/socket2/blob/1f70523b45a061560eb92a5510cfeed0a8e83de1/src/sys/windows.rs#L218-L227. In rust standard library: https://github.com/rust-lang/rust/blob/078eb1120a3f576598b976d9470701363f48fccc/library/std/src/sys/windows/net.rs#L36-L59

**Comment by ChrisDenton** [comment]
Is there a reason why WSAStartup isn't called directly? Being tied to the standard library's startup/shutdown seems less versatile and more hacky.

**Comment by Thomasdezeeuw** [comment]
> Is there a reason why WSAStartup isn't called directly? Being tied to the standard library's startup/shutdown seems less versatile and more hacky.

It's not really possible as standard library always calls the `WSAStartup` whenever a `std::net` type is used. Furthermore it will panic if the call to `WSAStartup` fails. So if socket2 would call `WSAStartup` itself any usage of a type in `std::net` would cause a panic.

**Comment by Thomasdezeeuw** [comment]
> `WSAStartup` can be successfully called multiple times. The std only panics if the call fails. Trivial example:

That certainly didn't use the be case. What Windows version are you using?

Some more background: https://github.com/tokio-rs/mio/issues/1046, https://github.com/tokio-rs/mio/pull/1029

**Comment by ChrisDenton** [comment]
I've not yet investigated that thread but it's[ documented behaviour](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup) so I'm surprised it didn't work.

> An application can call WSAStartup more than once if it needs to obtain the [WSADATA](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/ns-winsock-wsadata) structure information more than once. On each such call, the application can specify any version number supported by the Winsock DLL...
> An application must call the [WSACleanup](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsacleanup) function for every successful time the WSAStartup function is called.
