### ISSUE TITLE
bind_device succeeds, but subsequent sends fail with no such device or address.

### ISSUE THREAD

**Issue by Frostie314159** [rust-lang/socket2#473]
When using the bind_device command on a raw socket the command succeeds, but trying to send data over the socket results in "no such device or address".

**Comment by Thomasdezeeuw** [comment]
Have to checked that you're binding to a correct device?

Also for raw sockets I think some OS don't do the same level of checking that happens for other sockets, but I could be wrong here.

In any case it's a little hard to help without some code and knowing a bit more about the environment it's running.

**Comment by Frostie314159** [comment]
Yes I have. It fails on every device I tried. 
```
use socket2::{Socket, Domain, Type};
fn main() {
 let socket = Socket::new_raw(Domain::PACKET, Type::RAW, None).unwrap();
 socket.bind_device(Some("YOUR_INTERFACE_HERE".as_bytes())).unwrap();
 socket.send([0x00; 0xff].as_slice()).unwrap();
}
```

**Comment by Thomasdezeeuw** [comment]
Please see the manual of `SO_BINDTODEVICE` in `socket(7)`: https://www.man7.org/linux/man-pages/man7/socket.7.html. Specifically:

> Note that this  works only for some socket types, particularly AF_INET
> sockets.  It is not supported for packet sockets (use
> normal [bind(2)](https://www.man7.org/linux/man-pages/man2/bind.2.html) there).

**Comment by Thomasdezeeuw** [comment]
@Frostie314159 did you get it to work with IP sockets?

**Comment by Frostie314159** [comment]
I didn't try that yet, since I needed socket2 for raw sockets, but thanks anyway. I just use libpcap for my purpose right now.
