### ISSUE TITLE
QUESTION: How to special `laddr` when dialing connection?

### ISSUE THREAD

**Issue by jjeffcaii** [rust-lang/socket2#478]
In Golang, we can use codes below to specify the local addr:
```go
    // https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/net/udpsock.go;l=290
    srcAddr := &net.UDPAddr{IP: net.IPv4zero, Port: 9982}
    dstAddr := &net.UDPAddr{IP: net.ParseIP("207.148.70.129"), Port: 9981}
    conn, err := net.DialUDP("udp", srcAddr, dstAddr)
    if err != nil {
        fmt.Println(err)
    }
```

I didn't find similar methods in the `socket2` pkg, can anyone help?

**Comment by the8472** [comment]
socket2 mostly provides pretty straight-forward mappings to underlying OS APIs. The operation you're looking for is [bind](https://man7.org/linux/man-pages/man2/bind.2.html), which is [also called bind in socket2](https://docs.rs/socket2/0.5.5/socket2/struct.Socket.html#method.bind).

See the [socket(7)](https://man7.org/linux/man-pages/man7/socket.7.html) man page or [wikipedia](https://en.wikipedia.org/wiki/Berkeley_sockets) for a high level overview of the available functions.

**Comment by Thomasdezeeuw** [comment]
`laddr` stands for local address. You first need to `bind(2)` the socket to a local address, then call `connect(2)`.

As @the8472 mentioned If you want to use socket2 you need some knowledge of the underlying system calls, for which the linked manual pages and Wikipedia are a good starting point. Of course there is always the awesome Beej network guide: https://beej.us/guide/bgnet/ (arguably the best learning resource for using BSD sockets).

**Comment by jjeffcaii** [comment]
Thanks! ❤️
