### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Kofituo** [rust-lang/socket2#483]
Hi there, 
I wanted to know if this has worked on Android before. I'm currently facing an error when connecting to sockets

```
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }'
```

This is the line that triggers the error

```rust
let mut soc = Socket::new(Domain::IPV4, Type::STREAM, None).unwrap();
```

I'm calling the Rust method via JNI

**Comment by Thomasdezeeuw** [comment]
As far as I know socket2 works on Android. Consider it returns a `PermissionDenied` error the code works, but you don't have permission. Looking at https://stackoverflow.com/questions/6778103/a-simple-socket-app-in-android-needs-some-special-permissions-to-connect-through, I think your app needs the `INTERNET` permission to work.

However Android development is out of scope for this issue tracking, you might be better of searching stackoverflow or similar for android network programming.

**Comment by Kofituo** [comment]
Sockets work on android. The standard library's TcpStream works just fine. Even socket2 `Socket` works just fine. However, the code I posted in this issue doesn't work. So the issue isn't with sockets on android. I think it's more to do with how datalink channel was implemented. 

I also added the Internet permission by the way

**Comment by Kofituo** [comment]
I **wouldn't** consider this issue completed. You can go ahead and try out a simple socket implementation and then try out the example in the examples folder. You'd realise the issue I'm facing

**Comment by Thomasdezeeuw** [comment]
> Sockets work on android. The standard library's TcpStream works just fine. Even socket2 Socket works just fine. However, the code I posted in this issue doesn't work. So the issue isn't with sockets on android. I think it's more to do with how datalink channel was implemented.

The code you post is fine, nothing wrong with it.

> I also added the Internet permission by the way

Did this solve the issue?

> I **wouldn't** consider this issue completed. You can go ahead and try out a simple socket implementation and then try out the example in the examples folder. You'd realise the issue I'm facing

I'm not an Android dev, so I'm not going to do that as I don't have an environment set up for it, or an Android phone for that matter.

If you still think this is an issue with socket2 I'm willing to reopen it, but I'll need some more information.

**Comment by Kofituo** [comment]
I deleted my earlier comments. Sorry. I responded to the wrong issue
