### ISSUE TITLE
How to read EventExtra from the event?

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [rust-lang/socket2#490]
when creating TCP connection, sometimes there's no tcp server listening at the other end, then the event will be 
```
event=Event { key: 1, readable: true, writable: true, extra: EventExtra { flags: CONNECT_FAIL } }
```
when polled

How do I read this extra field of the event to know that it has failed.

**Comment by Thomasdezeeuw** [comment]
What event are you talking about? Socket2 doesn't provide any polling.
