### ISSUE TITLE
Possible to publish a new patch release?

### ISSUE THREAD

**Issue by tobz** [rust-lang/socket2#509]
I've been using a Cargo patch to pull in `master` to get #505 and #506, which have been working well for me in testing.

Would it be possible to cut a patch release that includes those two PRs?

**Comment by Thomasdezeeuw** [comment]
Doing this in https://github.com/rust-lang/socket2/pull/511.

**Comment by Thomasdezeeuw** [comment]
Published: https://crates.io/crates/socket2/0.5.7.

**Comment by tobz** [comment]
Awesome, thank you so much. 👍
