### ISSUE TITLE
Add rest of socket options for unix

### ISSUE THREAD

**Issue by Kleinmarb** [rust-lang/socket2#523]
There is #132 and #183 but these socket options are still missing:
SO_DONTROUTE,
SO_DEBUG,
SO_RCVLOWAT,
SO_SNDLOWAT,

I'm going to add these in unix.rs.

**Comment by Thomasdezeeuw** [comment]
There are many options missing, having a generic issue to "add the rest" I don't think will be helpful. Prs to add new options are welcome though.

**Comment by Thomasdezeeuw** [comment]
Closing this as it's too broad.
