### ISSUE TITLE
Question: socket.gethostname() functionality for this crate?

### ISSUE THREAD

**Issue by spamwax** [rust-lang/socket2#53]
I was just wondering if it makes sense to add a similar functionality to that of [python's](https://docs.python.org/3/library/socket.html#socket.gethostname) `socket` [module](https://github.com/python/cpython/blob/4ab362cec6/Modules/socketmodule.c#L5368-L5421) to this crate so the hostname (FQDN or not) of the machine (for the local end of) `socket` is returned? or this is something beyond/unrelated to this crate?

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

**Comment by spamwax** [comment]
Thanks
I'd like to tackle this.

any hints/directions on design of the API is appreciated. For example, should we support `gethostnmame()` for all possible combination of [Domain](https://docs.rs/socket2/0.3.11/socket2/struct.Domain.html), [Type](https://docs.rs/socket2/0.3.11/socket2/struct.Type.html) and [Protocol](https://docs.rs/socket2/0.3.11/socket2/struct.Protocol.html) that `socket2` offers or just focus on some?
(ex: does a`dgram` type `unix`-domain socket need to have access to `gethostname()`)

**Comment by Thomasdezeeuw** [comment]
@spamwax do you still need this? According to the manual glibc actually uses `uname(2)`, so something like Nix might be a better crates for this, they already have a wrapper function: https://docs.rs/nix/0.19.1/nix/sys/utsname/fn.uname.html.

**Comment by spamwax** [comment]
ok, thanks.
