### ISSUE TITLE
Socket2 use for Mio

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#56]
Hello I'm the maintainer of [Mio](https://crates.io/crates/mio) and I want to support some additional API around sockets. To not duplicate the effort around raw socket handling I think socket2 would be a good fit.

However I do have some questions. What is the status of maintenance of this crate? I've read @alexcrichton message some time ago that he'll be taking a step back from Rust (sorry to see you go and thanks for all you've done!). I'm willing to help maintain this crate if its a good fit for Mio.

I'm also looking to change the API a bit. I've being doing some experiments here: https://github.com/Thomasdezeeuw/socket2, diff: https://github.com/alexcrichton/socket2-rs/compare/master...Thomasdezeeuw:master. The basic idea follows the same philosophy as Mio with OS specific API: make setters only available on OSes that support it and getters on all platforms (returning a negative/false value if not supported). For example [`mio::Interest::LIO`](https://github.com/tokio-rs/mio/blob/7323d718b363077bdfa24ac24a6e93489295ae12/src/interest.rs#L52-L54) is only available on FreeBSD, but its getter is available on [all platforms](https://github.com/tokio-rs/mio/blob/7323d718b363077bdfa24ac24a6e93489295ae12/src/interest.rs#L88-L91).

Furthermore I would like to structure the code a bit differently. Moving the struct definitions to the same file as the commonly supported API, but move OS specific additional API to the `sys/` dir. For example the common API for `Domain`: https://github.com/Thomasdezeeuw/socket2/blob/279c289e0af232167c7b67560b6c64e60ef0069c/src/lib.rs#L63-L112. And the Unix specific API is located in `sys/unix.rs`: https://github.com/Thomasdezeeuw/socket2/blob/279c289e0af232167c7b67560b6c64e60ef0069c/src/sys/unix.rs#L32-L44.

Let me know what you guys think.

**Comment by Thomasdezeeuw** [comment]
An example how restructuring the API: #57.

**Comment by stjepang** [comment]
Hey everyone, another user relying on this crate chiming in - currently developing and wrapping up an alternative to mio (similar capabilities, but much simpler and 100% safe), which would not be possible without socket2, so here's another thank you!

I would also be interested in helping maintain this crate :)

**Comment by alexcrichton** [comment]
Hello and thanks for reaching out! I do indeed not necessarily have a ton of time (or interest at this point) to maintain this crate. I'm happy to help keep it alive though, and would love to have help if others are interested!

@sfackler has also helped out with this crate historically (I think? If not feel free to unsubscribe). I don't mind modernizing this and/or reorganizing it. I would like to keep the spirit of the crate though where it's an extremely thin wrapper around the OS without extra abstraction and such. Given what I've seen so far though it looks like that won't be an issue :)

Perhaps @Thomasdezeeuw and @stjepang y'all could help out with some PRs/reviews of those PRs and if everything looks good I can add y'all as maintainers?

**Comment by Thomasdezeeuw** [comment]
@alexcrichton sound good, I'll start sending prs and ping @stjepang for reviews (if you're OK with that @stjepang).

**Comment by stjepang** [comment]
Sounds great to me, let's do that!

**Comment by Thomasdezeeuw** [comment]
Continuing in #212.
