### ISSUE TITLE
New v0.3.x branch

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/socket2#97]
@stjepang I've pushed a new v0.3.x branch based on commit c22d0e55c4dff90ad1f0c6cfed6708cc79764408 (Bump to 0.3.12). Then I cherry-picked b3badc7d3d599746a3632666876f1a253476c3c7, 32969e53c75849e4047233d8b55f551a8645b21d, 7bf31f95af1905880e73a169b0eb3894597e6f0f, which are small fixes (and more importantly not API breaking!)

**Comment by Thomasdezeeuw** [comment]
I think its safe to release v0.3.15 from that branch, but maybe you want to take a look first.

**Comment by stjepang** [comment]
I confirm this looks good.

Diff between 0.3.12 and v0.3.x: https://github.com/alexcrichton/socket2-rs/compare/0.3.12..v0.3.x

**Comment by coolreader18** [comment]
Would it be feasible to publish 0.3.15 from the 0.3.x branch? It seems like there aren't any breaking changes in the diff, other than fixes for typos in functions that weren't really usable anyway.

**Comment by Thomasdezeeuw** [comment]
A new release sounds good to me, @stjepang what do you think?

**Comment by stjepang** [comment]
Let's do it!

**Comment by Thomasdezeeuw** [comment]
Created #100.

**Comment by Thomasdezeeuw** [comment]
@coolreader18 I just published v0.3.15.

**Comment by coolreader18** [comment]
Cool, thank you!

**Comment by linkmauve** [comment]
Hi, could you also backport 43b75d3dd4a90e33b4b9ddb764f84f68914c9648 please?  It prevents this crate from building under Haiku, blocking for instance cargo-c.

**Comment by Thomasdezeeuw** [comment]
@linkmauve would be could if you opened a pr :) Otherwise I can do it tomorrow.

**Comment by linkmauve** [comment]
Here, done in #115!

**Comment by coolreader18** [comment]
Could we release a 0.3.18 with the redox fixes?

**Comment by Thomasdezeeuw** [comment]
#178 add this to the README, so I'm going to close this.
